# Generated by Django 4.2.16 on 2024-11-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcatalogmodel_productmodel_product_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatalogmodel',
            name='catalog_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
