# Generated by Django 4.2.16 on 2024-11-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productcatalogmodel_catalog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='best_sellers',
            field=models.BooleanField(default=False),
        ),
    ]
