# Generated by Django 4.2.16 on 2024-11-19 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_productmodel_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=500, null=True)),
                ('current_user', models.CharField(blank=True, max_length=1000, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('status', models.CharField(blank=True, choices=[('InCart', 'In Cart'), ('Purchased', 'Purchased'), ('Complete', 'Complete'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='InCart', max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.productmodel')),
            ],
        ),
    ]
