# Generated by Django 4.2.16 on 2024-11-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('InCart', 'In Cart'), ('Order', 'Order'), ('Purchased', 'Purchased'), ('Complete', 'Complete'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='InCart', max_length=1000, null=True),
        ),
    ]
