# Generated by Django 4.2.16 on 2024-11-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitemsmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=500, null=True)),
                ('current_user', models.CharField(blank=True, max_length=1000, null=True)),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('street', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('province', models.CharField(max_length=200, null=True)),
                ('postal_code', models.CharField(max_length=200, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('status', models.CharField(blank=True, choices=[('Order', 'Order'), ('Purchased', 'Purchased'), ('Complete', 'Complete'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Oder', max_length=1000, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer_items', models.ManyToManyField(blank=True, default=None, related_name='customer_items', to='cart.cartitemsmodel')),
            ],
        ),
    ]
